//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestSoapProgram.ServiceReferenceTest {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style", ConfigurationName="ServiceReferenceTest.ZECP_WS_MARCA_VISUAL_ASIST")]
    public interface ZECP_WS_MARCA_VISUAL_ASIST {
        
        // CODEGEN: Generating message contract since the operation ZwsMarcaVisualAsist is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        TestSoapProgram.ServiceReferenceTest.ZwsMarcaVisualAsistResponse1 ZwsMarcaVisualAsist(TestSoapProgram.ServiceReferenceTest.ZwsMarcaVisualAsistRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<TestSoapProgram.ServiceReferenceTest.ZwsMarcaVisualAsistResponse1> ZwsMarcaVisualAsistAsync(TestSoapProgram.ServiceReferenceTest.ZwsMarcaVisualAsistRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZwsMarcaVisualAsist : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ZesMarcaVisual[] itMarcaField;
        
        private ZesResultado[] itResulField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZesMarcaVisual[] ItMarca {
            get {
                return this.itMarcaField;
            }
            set {
                this.itMarcaField = value;
                this.RaisePropertyChanged("ItMarca");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZesResultado[] ItResul {
            get {
                return this.itResulField;
            }
            set {
                this.itResulField = value;
                this.RaisePropertyChanged("ItResul");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZesMarcaVisual : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codigoTrabField;
        
        private string dniField;
        
        private string fechaField;
        
        private string eventoField;
        
        private string horaIniField;
        
        private string horaFinField;
        
        private string entradaField;
        
        private string salidaRefField;
        
        private string entradaRefField;
        
        private string salidaField;
        
        private string marcaAdc01Field;
        
        private string marcaAdc02Field;
        
        private string asistenciaField;
        
        private string jornadaField;
        
        private string refrigerioField;
        
        private string atrasoField;
        
        private string salidaTemField;
        
        private string ausenciaField;
        
        private string horasAdicField;
        
        private string horas25Field;
        
        private string horas35Field;
        
        private string horas100Field;
        
        private string horasTotField;
        
        private string horasNocField;
        
        private string justificacionField;
        
        private string inicioJustField;
        
        private string finJustField;
        
        private string totalHrsJustField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string CodigoTrab {
            get {
                return this.codigoTrabField;
            }
            set {
                this.codigoTrabField = value;
                this.RaisePropertyChanged("CodigoTrab");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Dni {
            get {
                return this.dniField;
            }
            set {
                this.dniField = value;
                this.RaisePropertyChanged("Dni");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string Fecha {
            get {
                return this.fechaField;
            }
            set {
                this.fechaField = value;
                this.RaisePropertyChanged("Fecha");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string Evento {
            get {
                return this.eventoField;
            }
            set {
                this.eventoField = value;
                this.RaisePropertyChanged("Evento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string HoraIni {
            get {
                return this.horaIniField;
            }
            set {
                this.horaIniField = value;
                this.RaisePropertyChanged("HoraIni");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string HoraFin {
            get {
                return this.horaFinField;
            }
            set {
                this.horaFinField = value;
                this.RaisePropertyChanged("HoraFin");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string Entrada {
            get {
                return this.entradaField;
            }
            set {
                this.entradaField = value;
                this.RaisePropertyChanged("Entrada");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string SalidaRef {
            get {
                return this.salidaRefField;
            }
            set {
                this.salidaRefField = value;
                this.RaisePropertyChanged("SalidaRef");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string EntradaRef {
            get {
                return this.entradaRefField;
            }
            set {
                this.entradaRefField = value;
                this.RaisePropertyChanged("EntradaRef");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string Salida {
            get {
                return this.salidaField;
            }
            set {
                this.salidaField = value;
                this.RaisePropertyChanged("Salida");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string MarcaAdc01 {
            get {
                return this.marcaAdc01Field;
            }
            set {
                this.marcaAdc01Field = value;
                this.RaisePropertyChanged("MarcaAdc01");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string MarcaAdc02 {
            get {
                return this.marcaAdc02Field;
            }
            set {
                this.marcaAdc02Field = value;
                this.RaisePropertyChanged("MarcaAdc02");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string Asistencia {
            get {
                return this.asistenciaField;
            }
            set {
                this.asistenciaField = value;
                this.RaisePropertyChanged("Asistencia");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string Jornada {
            get {
                return this.jornadaField;
            }
            set {
                this.jornadaField = value;
                this.RaisePropertyChanged("Jornada");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string Refrigerio {
            get {
                return this.refrigerioField;
            }
            set {
                this.refrigerioField = value;
                this.RaisePropertyChanged("Refrigerio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public string Atraso {
            get {
                return this.atrasoField;
            }
            set {
                this.atrasoField = value;
                this.RaisePropertyChanged("Atraso");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public string SalidaTem {
            get {
                return this.salidaTemField;
            }
            set {
                this.salidaTemField = value;
                this.RaisePropertyChanged("SalidaTem");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public string Ausencia {
            get {
                return this.ausenciaField;
            }
            set {
                this.ausenciaField = value;
                this.RaisePropertyChanged("Ausencia");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=18)]
        public string HorasAdic {
            get {
                return this.horasAdicField;
            }
            set {
                this.horasAdicField = value;
                this.RaisePropertyChanged("HorasAdic");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=19)]
        public string Horas25 {
            get {
                return this.horas25Field;
            }
            set {
                this.horas25Field = value;
                this.RaisePropertyChanged("Horas25");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=20)]
        public string Horas35 {
            get {
                return this.horas35Field;
            }
            set {
                this.horas35Field = value;
                this.RaisePropertyChanged("Horas35");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=21)]
        public string Horas100 {
            get {
                return this.horas100Field;
            }
            set {
                this.horas100Field = value;
                this.RaisePropertyChanged("Horas100");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=22)]
        public string HorasTot {
            get {
                return this.horasTotField;
            }
            set {
                this.horasTotField = value;
                this.RaisePropertyChanged("HorasTot");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=23)]
        public string HorasNoc {
            get {
                return this.horasNocField;
            }
            set {
                this.horasNocField = value;
                this.RaisePropertyChanged("HorasNoc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=24)]
        public string Justificacion {
            get {
                return this.justificacionField;
            }
            set {
                this.justificacionField = value;
                this.RaisePropertyChanged("Justificacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=25)]
        public string InicioJust {
            get {
                return this.inicioJustField;
            }
            set {
                this.inicioJustField = value;
                this.RaisePropertyChanged("InicioJust");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=26)]
        public string FinJust {
            get {
                return this.finJustField;
            }
            set {
                this.finJustField = value;
                this.RaisePropertyChanged("FinJust");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=27)]
        public string TotalHrsJust {
            get {
                return this.totalHrsJustField;
            }
            set {
                this.totalHrsJustField = value;
                this.RaisePropertyChanged("TotalHrsJust");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZesResultado : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codigoEstaField;
        
        private string mensajeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string CodigoEsta {
            get {
                return this.codigoEstaField;
            }
            set {
                this.codigoEstaField = value;
                this.RaisePropertyChanged("CodigoEsta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Mensaje {
            get {
                return this.mensajeField;
            }
            set {
                this.mensajeField = value;
                this.RaisePropertyChanged("Mensaje");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZwsMarcaVisualAsistResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ZesMarcaVisual[] itMarcaField;
        
        private ZesResultado[] itResulField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZesMarcaVisual[] ItMarca {
            get {
                return this.itMarcaField;
            }
            set {
                this.itMarcaField = value;
                this.RaisePropertyChanged("ItMarca");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZesResultado[] ItResul {
            get {
                return this.itResulField;
            }
            set {
                this.itResulField = value;
                this.RaisePropertyChanged("ItResul");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZwsMarcaVisualAsistRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style", Order=0)]
        public TestSoapProgram.ServiceReferenceTest.ZwsMarcaVisualAsist ZwsMarcaVisualAsist;
        
        public ZwsMarcaVisualAsistRequest() {
        }
        
        public ZwsMarcaVisualAsistRequest(TestSoapProgram.ServiceReferenceTest.ZwsMarcaVisualAsist ZwsMarcaVisualAsist) {
            this.ZwsMarcaVisualAsist = ZwsMarcaVisualAsist;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZwsMarcaVisualAsistResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style", Order=0)]
        public TestSoapProgram.ServiceReferenceTest.ZwsMarcaVisualAsistResponse ZwsMarcaVisualAsistResponse;
        
        public ZwsMarcaVisualAsistResponse1() {
        }
        
        public ZwsMarcaVisualAsistResponse1(TestSoapProgram.ServiceReferenceTest.ZwsMarcaVisualAsistResponse ZwsMarcaVisualAsistResponse) {
            this.ZwsMarcaVisualAsistResponse = ZwsMarcaVisualAsistResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ZECP_WS_MARCA_VISUAL_ASISTChannel : TestSoapProgram.ServiceReferenceTest.ZECP_WS_MARCA_VISUAL_ASIST, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ZECP_WS_MARCA_VISUAL_ASISTClient : System.ServiceModel.ClientBase<TestSoapProgram.ServiceReferenceTest.ZECP_WS_MARCA_VISUAL_ASIST>, TestSoapProgram.ServiceReferenceTest.ZECP_WS_MARCA_VISUAL_ASIST {
        
        public ZECP_WS_MARCA_VISUAL_ASISTClient() {
        }
        
        public ZECP_WS_MARCA_VISUAL_ASISTClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ZECP_WS_MARCA_VISUAL_ASISTClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ZECP_WS_MARCA_VISUAL_ASISTClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ZECP_WS_MARCA_VISUAL_ASISTClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TestSoapProgram.ServiceReferenceTest.ZwsMarcaVisualAsistResponse1 TestSoapProgram.ServiceReferenceTest.ZECP_WS_MARCA_VISUAL_ASIST.ZwsMarcaVisualAsist(TestSoapProgram.ServiceReferenceTest.ZwsMarcaVisualAsistRequest request) {
            return base.Channel.ZwsMarcaVisualAsist(request);
        }
        
        public TestSoapProgram.ServiceReferenceTest.ZwsMarcaVisualAsistResponse ZwsMarcaVisualAsist(TestSoapProgram.ServiceReferenceTest.ZwsMarcaVisualAsist ZwsMarcaVisualAsist1) {
            TestSoapProgram.ServiceReferenceTest.ZwsMarcaVisualAsistRequest inValue = new TestSoapProgram.ServiceReferenceTest.ZwsMarcaVisualAsistRequest();
            inValue.ZwsMarcaVisualAsist = ZwsMarcaVisualAsist1;
            TestSoapProgram.ServiceReferenceTest.ZwsMarcaVisualAsistResponse1 retVal = ((TestSoapProgram.ServiceReferenceTest.ZECP_WS_MARCA_VISUAL_ASIST)(this)).ZwsMarcaVisualAsist(inValue);
            return retVal.ZwsMarcaVisualAsistResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TestSoapProgram.ServiceReferenceTest.ZwsMarcaVisualAsistResponse1> TestSoapProgram.ServiceReferenceTest.ZECP_WS_MARCA_VISUAL_ASIST.ZwsMarcaVisualAsistAsync(TestSoapProgram.ServiceReferenceTest.ZwsMarcaVisualAsistRequest request) {
            return base.Channel.ZwsMarcaVisualAsistAsync(request);
        }
        
        public System.Threading.Tasks.Task<TestSoapProgram.ServiceReferenceTest.ZwsMarcaVisualAsistResponse1> ZwsMarcaVisualAsistAsync(TestSoapProgram.ServiceReferenceTest.ZwsMarcaVisualAsist ZwsMarcaVisualAsist) {
            TestSoapProgram.ServiceReferenceTest.ZwsMarcaVisualAsistRequest inValue = new TestSoapProgram.ServiceReferenceTest.ZwsMarcaVisualAsistRequest();
            inValue.ZwsMarcaVisualAsist = ZwsMarcaVisualAsist;
            return ((TestSoapProgram.ServiceReferenceTest.ZECP_WS_MARCA_VISUAL_ASIST)(this)).ZwsMarcaVisualAsistAsync(inValue);
        }
    }
}
